config/routes.rb
Rails.application.routes.draw do

  get 'test', to: 'static_pages#test', as: 'test'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy', as: 'signout'

  resources :trips
  resources :passports
  resources :account_profiles

  root 'static_pages#home'

end

app/models/account_profile.rb
# == Schema Information
#
# Table name: account_profiles
#
#  id             :integer          not null, primary key
#  last_name      :string
#  first_name     :string
#  middle_name    :string
#  date_of_birth  :date
#  martial_status :string
#  gender         :string
#  religion       :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class AccountProfile < ActiveRecord::Base
  validates_presence_of :first_name, :last_name, :date_of_birth, :martial_status
  validates :last_name, length: { minimum: 2 }

  has_many :passports

  # scope :marital_status, -> {where(marital_status: "single")}
  # scope :marital_status, -> (marital_status) { where( "marital_status < ?", marital_status)
end

app/models/passport.rb
# == Schema Information
#
# Table name: passports
#
#  id                   :integer          not null, primary key
#  last_name            :string
#  given_name           :string
#  passport_number      :string
#  date_of_issue        :date
#  date_of_expiration   :date
#  authority            :string
#  type                 :string
#  place_of_birth       :string
#  number_of_visa_pages :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  country_of_issue     :string
#  profile_id           :integer
#

class Passport < ActiveRecord::Base
  validates_presence_of :given_name, :last_name, :date_of_birth, :marital_status,
  :date_of_birth, :authority, :date_of_issue, :date_of_expiration, :number_of_visa_pages,
  :type, :country_of_issue

  belongs_to :profile
  has_many :visas
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id             :integer          not null, primary key
#  last_name      :string
#  first_name     :string
#  middle_name    :string
#  date_of_birth  :date
#  marital_status :string
#  gender         :string
#  religion       :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Profile < ActiveRecord::Base
  validates_presence_of :first_name, :last_name, :date_of_birth, :marital_status
  validates :last_name, length: { minimum: 2 }

  has_many :passports

  # scope :marital_status, -> {where(marital_status: "single")}
  # scope :marital_status, -> (marital_status) { where( "marital_status < ?", marital_status)}
end

app/models/trip.rb
# == Schema Information
#
# Table name: trips
#
#  id         :integer          not null, primary key
#  trip_name  :string
#  start_date :date
#  end_date   :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Trip < ActiveRecord::Base
  validates_presence_of :trip_name

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  provider   :string
#  uid        :string
#  name       :string
#  location   :string
#  image_url  :string
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  def self.from_omniauth(auth_hash)
    uid = auth_hash['uid']
    provider = auth_hash['provider']

    user = User.find_or_create_by(uid: uid, provider: provider)
    user.name = auth_hash['info']['name']
    user.location = auth_hash['info']['location']
    user.image_url = auth_hash['info']['image']
    user.url = auth_hash['info']['urls']['Twitter']

    user.save!
    return user
  end
end

app/models/visa.rb
# == Schema Information
#
# Table name: visas
#
#  id                 :integer          not null, primary key
#  country            :string
#  date_of_issue      :date
#  date_of_expiration :date
#  duration           :integer
#  visa_type          :string
#  passport_id        :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Visa < ActiveRecord::Base
  belongs_to :passport

  validates_presence_of :country
end

app/controllers/account_profiles_controller.rb
class AccountProfilesController < ApplicationController
  def index
    @account_profiles = AccountProfile.all
  end

  def new
    @account_profile = AccountProfile.new
  end

  def create
    @account_profile = AccountProfile.new(account_profile_params)
      if @account_profile.save
      redirect_to account_profiles_path
      else
        render "new"
      end
  end

  def edit
    @account_profile = get_account_profile
  end

  def update
    @account_profile = get_account_profile
    if @account_profile.update(account_profile_params)
      redirect_to account_profiles_path, notice: "Profile updated"
    else
      render "edit"
    end
  end

  def delete
    @account_profile = get_account_profile
    @account_profile.destroy
    redirect_to account_profiles_path
  end

  private
  def get_account_profile
    AccountProfile.find(params[:id])
  end

  def account_profile_params
    params.require(:account_profile).permit(:last_name, :first_name, :middle_name, :date_of_birth, :martial_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user
end

app/controllers/passports_controller.rb
class PassportsController < ApplicationController
  def index
    @passport = Passport.all
  end

  def show
    @passport = get_passport
  end

  def new
      @passport = Passport.new
  end

  def create
    @passport = Passport.new(passport_params)
    if @passport.save
    redirect_to passport_new_path
    else
      render "new"
    end
  end

  def edit
    @passport = get_passport
  end

  def destroy
    @passport = get_passport
    @passport.destroy
    redirect_to passport_new_path
  end

private
  def get_passport
    Passport.find(params[:id])
  end

  def passport_params
    params.require(:passport_number, :date_of_issue, :date_of_expiration)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    begin
      auth_hash = request.env['omniauth.auth']
      @user = User.from_omniauth(auth_hash)
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}"
  rescue
    flash[:warning] = "There was an error"
  end
  redirect_to account_profiles_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = "You are logged out!"
    end
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def test
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trip = Trip.all
  end

  def new
    @trip = Trip.new
  end

  def create
  @trip = Trip.new(trip_params)
    if @trip.save
      redirect_to trips_path
    else
      render "new"
    end
  end

  def edit
    @trip = get_trip
  end

  def update
    @trip = get_trip
      if @trip.update(trip_params)
        redirect_to trips_path, notice: "Trip Updated"
      else
        render "edit"
      end
  end

  def delete
    @trip = get_trip
    @trip.destroy
    redirect_to trips_path
  end

  private
  def get_trip
    Trip.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:trip_name, :start_date, :end_date)
  end
end

app/helpers/account_profiles_helper.rb
module AccountProfilesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passports_helper.rb
module PassportsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/account_profiles/_form.html.erb
<div class="panel-body">

<%= simple_form_for @account_profile do  |f| %>
  <%= f.input :last_name, label: false, input_html: { placeholder: "Last Name"} %>
  <%= f.input :first_name, label: false, input_html: { placeholder: "First Name"} %>
  <%= f.input :middle_name, label: false, input_html: { placeholder: "Middle Name" } %>
  <%= f.input :martial_status, label: false, input_html: { placeholder: "Marital Status" } %>

  <%= f.input :date_of_birth, :as => :date, :start_year => 1776 %>
  <%= f.submit "Submit".html_safe, class: "btn btn-lg btn-danger" %>
  <% end %>
</div>

app/views/account_profiles/edit.html.erb
<h1>Edit Account Profile</h1>

<%= render "form" %>

app/views/account_profiles/index.html.erb
<h1>Account Profiles </h1>
<t1> <%= link_to "Update Profile", "#", class: "btn" %> </t1>

<% @account_profiles.each do |account| %>
<li> <%= account.first_name %> </li>
<li> <%= account.middle_name %> </li>
<li> <%= account.last_name %> </li>
<li> <%= account.date_of_birth %> </li>
<li> <%= account.martial_status %> </li>

<%end %>

app/views/account_profiles/new.html.erb
<h1>New Account Profile </h1>

<%= render "form" %>

app/views/layouts/_main_nav.html.erb
<nav class="navbar navbar-default",>
  <div class="container-fluid",>
      <div class="navbar-header",>
        <button type "button" class='navbar-toggle collapsed','satisfy', data-toggle='collapse'
        data-target="#bs-example-navbar-1">
        <span class="sr-only"> Toggle Navigation </span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "iPassport", root_path, class: "navbar-brand Amatic" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
        <ul class="nav navbar-nav pull-right">
          <li> <%=link_to "My Profile", account_profiles_path %></li>
          <li> <%=link_to "New Profile", new_account_profile_path %></li>
          <li> <%=link_to "My Passports", '#' %></li>
          <li> <%=link_to "Update Profile", '#'%></li>
          <li> <%=link_to "My Trips", trips_path %></li>
          <li> <%=link_to "New Trip!", new_trip_path, class:"active" %></li>
          <li> <%=image_tag current_user.image_url, alt: current_user.name %> </li>
          <li> <%=link_to 'Sign Out', signout_path, class: 'btn btn-xs', method: :delete %> </li>
        </ul>
        <% else %>
        <ul class="nav navbar-nav pull-right">
          <li> <%= link_to 'Sign in', '/auth/twitter', class: 'btn btn-lg' %> </li>
          <li> <%=link_to "Test", test_path, class: 'btn btn-lg' %> </li>

        </ul>
        <% end %>
      </ul>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>iPassport</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media:
   'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application',
  'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= render 'layouts/main_nav' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/static_pages/home.html.erb
<h1 class="satisfy">iPassport</h1>

<h2 class="vtgreen"> Hello, World...</h2>

<%= image_tag("pie3.jpg") %>

app/views/static_pages/test.html.erb
<h1 class='satisfy'>Test Page</h1>
<p>This is the beginning of iPassport</p>
<p>This is a Test</p>

app/views/trips/_form.html.erb
<div class="panel-body">

<%= simple_form_for @trip do  |t| %>
  <%= t.input :trip_name, label: false, input_html: { placeholder: "Trip Name"} %>
  <%= t.input :start_date, :as => :date, :start_year => 1776, label: false, input_html: { placeholder: "Start Date"} %>
  <%= t.input :end_date, :as => :date, :start_year => 1776, label: false, input_html: { placeholder: "End Date" } %>

  <%= t.submit "Submit".html_safe, class: "btn btn-lg btn-danger" %>
  <% end %>
</div>

app/views/trips/index.html.erb
<% @trip.each do |trip| %>
<h2 class = "tangerine_bold"> <%= trip.trip_name %> </h2>
<li> <%= trip.start_date %> </li>
<li> <%= trip.end_date %> </li>

<%end %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render "form" %>